import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { Counter } from '../features/Counter/Counter'
import styles from '../styles/Home.module.css'
import Products from './products'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossOrigin="anonymous" />

      </Head>

      <main >
        <Products />
      </main>
    </div>
  )
}

export default Home
